# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_wrangling_agent
# Time Created: 2025-07-05 20:37:06

def data_wrangler(data_list):
    import pandas as pd
    import numpy as np
    '''
    Wrangle the data provided in data.
    
    data_list: A list of one or more pandas data frames containing the raw data to be wrangled.
    '''


    # Ensure the input is a list; if not, convert it to a list
    if not isinstance(data_list, list):
        data_list = [data_list]

    # Concatenate all dataframes in the list into a single dataframe
    combined_data = pd.concat(data_list, ignore_index=True)
    
    # Step 1: Select relevant columns
    filtered_data = combined_data[['ServiceName', 'Quantity', 'Cost']]
    
    # Step 2: Group by ServiceName
    grouped_data = filtered_data.groupby('ServiceName')
    
    # Step 3: Aggregate Quantity and Cost
    # Summing up Quantity and Cost for each ServiceName
    aggregated_data = grouped_data.agg({'Quantity': 'sum', 'Cost': 'sum'})
    
    # Step 4: Reset index to make 'ServiceName' a column again
    final_data_frame = aggregated_data.reset_index()
    
    # Step 5: Ensure the final data frame has the correct columns
    final_data_frame.columns = ['ServiceName', 'Quantity', 'Cost']

    # Return the finalized DataFrame
    return final_data_frame